"""Add print_detail() method in Freebie

Revision ID: 66bc32f5c035
Revises: 42855bda721b
Create Date: 2023-08-05 13:01:57.993992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66bc32f5c035'
down_revision = '42855bda721b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
